### ISSUE TITLE
ViewPagerAndroid has been extracted from react-native core（ "react-native": "0.60.0-rc.2"）

### ISSUE THREAD

**Issue by Michael-lu-ke** [ptomasroos/react-native-scrollable-tab-view#1018]
- [ ] I have searched [existing issues](https://github.com/happypancake/react-native-scrollable-tab-view/issues)
- [ ] I am using the [latest scrollable tab view version](https://www.npmjs.com/package/react-native-scrollable-tab-view)

**Comment by Michael-lu-ke** [comment]
The Android project is not working

**Comment by laurentS** [comment]
See https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/1019#issuecomment-510486204 for a temporary fix.

**Comment by ptomasroos** [comment]
Released as 1.0.0
