### ISSUE TITLE
Incompatible With React Native 0.61 Due to ViewPagerAndroid

### ISSUE THREAD

**Issue by AlexK777** [ptomasroos/react-native-scrollable-tab-view#1035]
- [x] I have searched [existing issues](https://github.com/happypancake/react-native-scrollable-tab-view/issues)
- [x] I am using the [latest scrollable tab view version](https://www.npmjs.com/package/react-native-scrollable-tab-view)

`ViewPagerAndroid` is deprecated and has been pulled out of core `react-native`. `react-native-viewpager` should be used instead and needs to be required from `https://github.com/react-native-community/react-native-viewpager`. 

## Steps to Reproduce
Build an application which uses this library on react-native version `0.61`.

## Expected Behavior
Library should be compatible. 

## Actual Behavior
Invariant violation for `ViewPagerAndroid`.

![Screenshot_1568858643](https://user-images.githubusercontent.com/7462060/65207830-b0d16180-da58-11e9-80b7-bc3d9eaac507.png)

**Comment by orcunorcun** [comment]
Can you change and release it, please?

**Comment by orcunorcun** [comment]
Same issue. Can you change and release it, please?

**Comment by jayshooo** [comment]
I had the same problem. So I made a pull request.
Hopefully it will merge.

https://github.com/ptomasroos/react-native-scrollable-tab-view/pull/1038

**Comment by ivanguimam** [comment]
same problem

**Comment by mokai** [comment]
+1

**Comment by snail714** [comment]
+1

**Comment by 18605161612** [comment]
+1

**Comment by orcunorcun** [comment]
Please merge @jayshooo 's PR. It's looks working well.

**Comment by ahmedakmal525** [comment]
Please merge @jayshooo 's [PR](https://github.com/ptomasroos/react-native-scrollable-tab-view/pull/1038)

**Comment by Houman7601** [comment]
same issue

**Comment by oneppiece** [comment]
Please merge @jayshooo 's PR.

**Comment by longnk-1447** [comment]
> I had the same problem. So I made a pull request.
> Hopefully it will merge.
> 
> #1038

not working in android? ios worked

**Comment by ptomasroos** [comment]
We're waiting on PR to land in order to fix this

**Comment by ptomasroos** [comment]
This is fixed in master, will be released as a new version in any day.

**Comment by lukewlms** [comment]
In the meantime you can get the change like this:

`yarn add https://github.com/ptomasroos/react-native-scrollable-tab-view#8ac09a9dee6c05906e9bfea8b4c736d3d5707a30`

**Comment by nonotest** [comment]
hello,
just wondering if anyone else had to add viewpager as a dependency to their root project for this to work?
Kept getting requireNativeComponent : "RNCViewPager" was not found in the UIManager" without it.
Thanks!

**Comment by zmnv** [comment]
@nonotest I have it too. 
https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/1050

**Comment by xuho** [comment]
> hello,
> just wondering if anyone else had to add viewpager as a dependency to their root project for this to work?
> Kept getting requireNativeComponent : "RNCViewPager" was not found in the UIManager" without it.
> Thanks!

same issue with you, did you fixed it?

**Comment by bdent** [comment]
> > hello,
> > just wondering if anyone else had to add viewpager as a dependency to their root project for this to work?
> > Kept getting requireNativeComponent : "RNCViewPager" was not found in the UIManager" without it.
> > Thanks!
> 
> same issue with you, did you fixed it?

-

> @nonotest I have it too.
> #1050 

-

> hello,
> just wondering if anyone else had to add viewpager as a dependency to their root project for this to work?
> Kept getting requireNativeComponent : "RNCViewPager" was not found in the UIManager" without it.
> Thanks!

-

Did either of you get this fixed?

**Comment by roysG** [comment]
Still problem! any update?
