### ISSUE TITLE
is there a plan to Publish a new version on npm ?

### ISSUE THREAD

**Issue by KingAmo** [ptomasroos/react-native-scrollable-tab-view#1047]
- [x] I have searched [existing issues](https://github.com/happypancake/react-native-scrollable-tab-view/issues)
- [x] I am using the [latest scrollable tab view version](https://www.npmjs.com/package/react-native-scrollable-tab-view)

is there a plan to publish a new version on `npm` ?  the last publish is a year ago and the master branch fixed may bugs

**Comment by ptomasroos** [comment]
Released as 1.0.0 breaking change

**Comment by KingAmo** [comment]
@ptomasroos would you please give a change log ? or update the `readme` ?

**Comment by ptomasroos** [comment]
This project has always been using the release tab.
https://github.com/ptomasroos/react-native-scrollable-tab-view/releases

**Comment by ptomasroos** [comment]
If you wanna compare to tag's here a tip 
https://github.com/ptomasroos/react-native-scrollable-tab-view/compare/v0.10.0%E2%80%A6/v1.0.0
