### ISSUE TITLE
onChangeTab fires twice

### ISSUE THREAD

**Issue by aykutcan** [ptomasroos/react-native-scrollable-tab-view#1060]
- [* ] I have searched [existing issues](https://github.com/happypancake/react-native-scrollable-tab-view/issues)
- [* ] I am using the [latest scrollable tab view version](https://www.npmjs.com/package/react-native-scrollable-tab-view)

onChangeTab event fires twice on Android. I don't know about IOS yet but Android is misbehaving right now. i m using 1.0.0

## Steps to Reproduce
Create New React Native Project

Add Missing Dependency @react-native-community/viewpager
`npm install @react-native-community/viewpager --save`

Copy [Scrollable Tabs Example](https://github.com/ptomasroos/react-native-scrollable-tab-view/blob/master/Example/ScrollableTabsExample.js)

## Expected Behavior
onChangeTab should fire once.

## Actual Behavior
onChangeTab fires twice for every tab click.

![image](https://user-images.githubusercontent.com/98998/69290236-5a2b0400-0c10-11ea-89f4-0967f9b3988e.png)

**Comment by LeoLei** [comment]
I got the same!

**Comment by tayguohong** [comment]
> I got the same! But found that, the second calling params had 'from' == 'i'.
> 
> So, temporarily solved by:
> 
> `... onChangeTab={ ({ i, from }) => i != from && tabChangeHandler(i) } ...`

Can you post your code for tabChangeHandler method? I am facing this issue too

**Comment by aykutcan** [comment]
> > I got the same! But found that, the second calling params had 'from' == 'i'.
> > So, temporarily solved by:
> > `... onChangeTab={ ({ i, from }) => i != from && tabChangeHandler(i) } ...`
> 
> Can you post your code for tabChangeHandler method? I am facing this issue too

with this way onChangeTab should call tabChangeHandler only once. So it should literally nothing but what you want in that method.

**Comment by tayguohong** [comment]
> > > I got the same! But found that, the second calling params had 'from' == 'i'.
> > > So, temporarily solved by:
> > > `... onChangeTab={ ({ i, from }) => i != from && tabChangeHandler(i) } ...`
> > 
> > 
> > Can you post your code for tabChangeHandler method? I am facing this issue too
> 
> with this way onChangeTab should call tabChangeHandler only once. So it should literally nothing but what you want in that method.

Ok, i will try on that, thank you.

**Comment by tayguohong** [comment]
> > > > I got the same! But found that, the second calling params had 'from' == 'i'.
> > > > So, temporarily solved by:
> > > > `... onChangeTab={ ({ i, from }) => i != from && tabChangeHandler(i) } ...`
> > > 
> > > 
> > > Can you post your code for tabChangeHandler method? I am facing this issue too
> > 
> > 
> > with this way onChangeTab should call tabChangeHandler only once. So it should literally nothing but what you want in that method.
> 
> Ok, i will try on that, thank you.

That solutions is working, thanks for everyone's help

**Comment by mickyguo** [comment]
> solutions



> > > > > I got the same! But found that, the second calling params had 'from' == 'i'.
> > > > > So, temporarily solved by:
> > > > > `... onChangeTab={ ({ i, from }) => i != from && tabChangeHandler(i) } ...`
> > > > 
> > > > 
> > > > Can you post your code for tabChangeHandler method? I am facing this issue too
> > > 
> > > 
> > > with this way onChangeTab should call tabChangeHandler only once. So it should literally nothing but what you want in that method.
> > 
> > 
> > Ok, i will try on that, thank you.
> 
> That solutions is working, thanks for everyone's help

Can you post your code for tabChangeHandler method? I am facing this issue too

**Comment by tayguohong** [comment]
@mickyguo  Here it is.
handleChangeTab(i, ref, from){
        console.log(i);
    }

Basically i just want to log it to check whether it fires once or not.

**Comment by mharrison-nzme** [comment]
> I got the same! But found that, the second calling params had 'from' == 'i'.
> 
> So, temporarily solved by:
> 
> `... onChangeTab={ ({ i, from }) => i != from && tabChangeHandler(i) } ...`

Solved it for me, thank you
