### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager

### ISSUE THREAD

**Issue by rachit2501** [ptomasroos/react-native-scrollable-tab-view#1069]
On running my appication it gives the follwing error :
ExceptionsManager.js:44 Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

This error is located at:
    in RNCViewPager (at ViewPager.js:150)
    in ViewPager (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-scrollable-tab-view/index.js:253)
    in RCTView (at react-native-scrollable-tab-view/index.js:396)
    in ScrollableTabView (at main.js:7)
    in Main (at src/index.js:21)
    in Provider (at src/index.js:20)
    in Root (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

You can check out the error from using my code : https://github.com/rachit2501/Sweat-Book commit 8d88b27 in the main.js file in src/container.

Ideally , the component should get rendered.

**Comment by zikwall** [comment]
Here is the fix for this error.

https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/1050#issuecomment-551376517

**Comment by rachit2501** [comment]
Thank you . I probably missed this issue during my search.

**Comment by ansarikhurshid786** [comment]
is it working for you ?

**Comment by hu-qi** [comment]
```yarn add @react-native-community/viewpager```
it worked for me.
"@react-native-community/viewpager": "^4.2.0",

![image](https://user-images.githubusercontent.com/17986122/97653164-1a64d180-1a9b-11eb-839a-266c6b1d56de.png)
