### ISSUE TITLE
AndroidX support need react-native-viewpager 3.x

### ISSUE THREAD

**Issue by victor-h** [ptomasroos/react-native-scrollable-tab-view#1071]
![image](https://user-images.githubusercontent.com/4351768/71797409-f27a2c80-3088-11ea-9fc8-6fb0308c7669.png)
用的AndroidX，需要react-native-viewpager 3.0以上版本，此项目中用的是2.0.2的，有什么解决办法吗？

**Comment by youngjuning** [comment]
+1

**Comment by w13808604** [comment]
+1

**Comment by ptomasroos** [comment]
+1

**Comment by congtaoa** [comment]
+1

**Comment by jpmaheux** [comment]
a PR already exists for this issue  https://github.com/ptomasroos/react-native-scrollable-tab-view/pull/1067

**Comment by ptomasroos** [comment]
#1067 is now merged
