### ISSUE TITLE
Tab content view is blank in android only

### ISSUE THREAD

**Issue by ansarikhurshid786** [ptomasroos/react-native-scrollable-tab-view#1077]
This is a really very nice library. I am using it. it working perfectly in ios. Today I run in android blank tab content in android. 

Does anyone face same issue.

**Comment by ansarikhurshid786** [comment]
I am using https://docs.nativebase.io/Components.html#tabs-def-headref. it working perfectly

**Comment by nishaQueppelin** [comment]
@ansarikhurshid786  I am facing same issue
Did you remove the library and used native base component

**Comment by nishaQueppelin** [comment]
> I am using https://docs.nativebase.io/Components.html#tabs-def-headref. it working perfectly

 I am facing same issue
Did you remove the library and used native base component
