### ISSUE TITLE
Does this library still work?

### ISSUE THREAD

**Issue by quangas** [ptomasroos/react-native-scrollable-tab-view#1083]
Just tried some samples/examples and despite the tab bar displaying the links ok, the body content is just blank (even something simple as Text or View). Anu ideas?

**Comment by shystruk** [comment]
Examples might be broken but Tabs are working fine. You may face some view issues :) Just try and let me know if you find something better ;)

**Comment by DeVoresyah** [comment]
I wanna try this but I'm worried it's not compatible with rn 0.61.+
is there any demo to check?

**Comment by nabilfreeman** [comment]
I've been using this successfully up to React Native 0.59 for https://github.com/lesalonapp.

Currently doing a huge upgrade to 0.61. I'll post back here after I've tested this library

**Comment by DeVoresyah** [comment]
thanks man @nabilfreeman

**Comment by ratihshav** [comment]
is there any updates on 0.61?

**Comment by jpmaheux** [comment]
I'm using it with rn 0.61.5 and its working fine, just had to add @react-native-community/viewpager to target v3.x as PR [1067](https://github.com/ptomasroos/react-native-scrollable-tab-view/pull/1067) is not merged yet

**Comment by ptomasroos** [comment]
#1067 is now merged. feel free to try out the master branch and report back any issues before a release

**Comment by DeVoresyah** [comment]
how about the demo? could you also please update the demo?

**Comment by nabilfreeman** [comment]
Awesome! just got round to testing it and it's working on 61 without the update as long as that dep is added.

Great job on keeping this maintained, we are excited to keep using it 🏆

**Comment by ptomasroos** [comment]
Thanks for leaving feedback @nabilfreeman

**Comment by DeVoresyah** [comment]
thanks for the info @nabilfreeman 
I also make a fw but nobody use it xD
