### ISSUE TITLE
Upgraded to React Native 0.62.0 Getting Warning Sign - "Calling `getNode()`

### ISSUE THREAD

**Issue by lucasluca** [ptomasroos/react-native-scrollable-tab-view#1085]
ReactNativeFiberHostComponent: Calling `getNode()` on the ref of an Animated component 
is no longer necessary. You can now directly use the ref instead. 
This method will be removed in a future release.

this happend on change tabs

**Comment by jinhongyu156** [comment]
me too

**Comment by ejdigby** [comment]
+1

**Comment by Malikkhoja** [comment]
+1

**Comment by ejdigby** [comment]
#1090 has been merged to fix this. Issue can now be closed

**Comment by brambang** [comment]
this update is create new problem, me and someone had same issue.
my problem is `this.scrollView.setPage is not function`
other man is `this.scrollView.scrollTo is not function`
but this same issue, because getNode() deleted.

My solution is, put getNode() back

**Comment by deot** [comment]
[Animated: Forward Ref to Component](https://github.com/facebook/react-native/commit/66e72bb4e00aafbcb9f450ed5db261d98f99f82a)
### temporary solution：
`this.scrollView.scrollTo` -> `this.scrollView._component.scrollTo`

**Comment by iamvucms** [comment]
This issue will make your app crash on  react native 0.65, let's add this patch file to fix
```
diff --git a/node_modules/react-native-scrollable-tab-view/index.js b/node_modules/react-native-scrollable-tab-view/index.js
index 82e53c5..36213dd 100644
--- a/node_modules/react-native-scrollable-tab-view/index.js
+++ b/node_modules/react-native-scrollable-tab-view/index.js
@@ -137,14 +137,14 @@ const ScrollableTabView = createReactClass({
     if (Platform.OS === 'ios') {
       const offset = pageNumber * this.state.containerWidth;
       if (this.scrollView) {
-        this.scrollView.getNode().scrollTo({x: offset, y: 0, animated: !this.props.scrollWithoutAnimation, });
+        this.scrollView.scrollTo({x: offset, y: 0, animated: !this.props.scrollWithoutAnimation, });
       }
     } else {
       if (this.scrollView) {
         if (this.props.scrollWithoutAnimation) {
-          this.scrollView.getNode().setPageWithoutAnimation(pageNumber);
+          this.scrollView.setPageWithoutAnimation(pageNumber);
         } else {
-          this.scrollView.getNode().setPage(pageNumber);
+          this.scrollView.setPage(pageNumber);
         }
       }
     }

```
