### ISSUE TITLE
Invariant Violation: requireNativeComponent "RNCViewPager"  was not found in the UIManager

### ISSUE THREAD

**Issue by Bayramito** [ptomasroos/react-native-scrollable-tab-view#1100]
Hello,

after i updated my project in react native i started to get this error in the places where i used ScrollableTabView.

RN: 0.62 (latest)
ScrollableTabView 1.0.0

**Comment by Dmitriy001** [comment]
@Bayramito yarn add @react-native-community/viewpager

**Comment by personwu0755** [comment]
I made the same mistake
after install @react-native-community/viewpager
run “react-native run-android”
An “ Could not find com.github.troZee:ViewPager2:v1.0.6.”   error occurred

**Comment by jiyuan12354** [comment]
> yarn add @react-native-community/viewpager

after `yarn add @react-native-community/viewpager`  and viewpager version is 4.0.0,  the error is gone, but my page is blank.

**Comment by chenxianj** [comment]
The same error occurred  while installing react-native-scrollable-tab-view by "npm install", and my version of react-native is 0.62.
It doesn't work even if I run "yarn add @react-native-community/viewpager".
Hope to get a solution as soon as ever, thanks.

**Comment by adamivancza** [comment]
You'll need to use version 3.3.0 of `@react-native-community/viewpager`

**Comment by cham1985** [comment]
> You'll need to use version 3.3.0 of `@react-native-community/viewpager`

Thank you for your help. The problem has been solved
