### ISSUE TITLE
如何自定义tab文字的样式呢，不仅仅是改变字体颜色和粗细。而是完全自定义？

### ISSUE THREAD

**Issue by weishisi** [ptomasroos/react-native-scrollable-tab-view#1112]
- [ ] I have searched [existing issues](https://github.com/happypancake/react-native-scrollable-tab-view/issues)
- [ ] I am using the [latest scrollable tab view version](https://www.npmjs.com/package/react-native-scrollable-tab-view)

**Comment by vobear** [comment]
<ScrollableTabView
          ref={(c) => {
            this.tabView = c;
          }}
          renderTabBar={() => (
            <CustomTabBar
              tabs={labelList}
            />
          )}  //自定义的tab
        >
          {labelList.map((item, index) => {
            return (
              <View>
              item
              </View>
            );
          })}
        </ScrollableTabView>
