### ISSUE TITLE
If  hava multiple flatlist is inside ScrollableTabView  it will share a maximum height 

### ISSUE THREAD

**Issue by Xujalg** [ptomasroos/react-native-scrollable-tab-view#1162]
- [x] I have searched [existing issues](https://github.com/happypancake/react-native-scrollable-tab-view/issues)
- [x] I am using the [latest scrollable tab view version](https://www.npmjs.com/package/react-native-scrollable-tab-view)

**Comment by qamraaan** [comment]
@Xujalg, good day to you! Have you managed to fix this issue?

**Comment by Xujalg** [comment]
> @Xujalg, good day to you! Have you managed to fix this issue?

Sorry, I left this project and forgot how to handle it. Unfortunately, I can't help you

**Comment by qamraaan** [comment]
@Xujalg, thank you, anyways!

**Comment by Xujalg** [comment]
> @Xujalg, thank you, anyways!

You're welcome. I can't help you either.
