### ISSUE TITLE
scrollView.getNode

### ISSUE THREAD

**Issue by yanyulin** [ptomasroos/react-native-scrollable-tab-view#1183]
- [ ] I have searched [existing issues](https://github.com/happypancake/react-native-scrollable-tab-view/issues)
- [ ] I am using the [latest scrollable tab view version](https://www.npmjs.com/package/react-native-scrollable-tab-view)

**Comment by SmileYang966** [comment]
这个需要更改源码。找到eact-native-scrollable-tab-view源码下的index文件夹,
this.scrollView.getNode().scrollTo改成this.scrollView.scrollTo，需要删除getNode()，我这边能正常工作
