### ISSUE TITLE
ViewPropTypes will be removed from React Native

### ISSUE THREAD

**Issue by SmileYang966** [ptomasroos/react-native-scrollable-tab-view#1186]
Issue1 : 
[ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types](https://stackoverflow.com/questions/71702392/viewproptypes-will-be-removed-from-react-native-migrate-to-viewproptypes-export)

solution:
1. yarn add deprecated-react-native-prop-types
2. We have to modify the source code, open every js source file, and do the following replacment
import {ViewPropTypes} from 'deprecated-react-native-prop-types';
or not 
const { ViewPropTypes } = ReactNative = require('react-native');

Issue2:
[TypeError: undefined is not an object (evaluating '_reactNative.Text.propTypes.style')](https://stackoverflow.com/questions/61226530/typeerror-undefined-is-not-an-object-evaluating-reactnative-animated-text-pr)
const ScrollableTabBar = createReactClass({
  propTypes: {
    goToPage: PropTypes.func,
    activeTab: PropTypes.number,
    tabs: PropTypes.array,
    backgroundColor: PropTypes.string,
    activeTextColor: PropTypes.string,
    inactiveTextColor: PropTypes.string,
    scrollOffset: PropTypes.number,
    style: ViewPropTypes.style,
    tabStyle: ViewPropTypes.style,
    tabsContainerStyle: ViewPropTypes.style,
    **textStyle: Text.propTypes.style,**
    renderTab: PropTypes.func,
    underlineStyle: ViewPropTypes.style,
    onScroll: PropTypes.func,
  },

textStyle: Text.propTypes.style ，I just choose to replace it by 'textStyle: ViewPropTypes.style', it work and the error was gone
You might need to change this in many source files.

Issue3:
ScrollView.getNode is undefined 

 We need to find the source code in react-native-scrollable-tab-view folder,
this.scrollView.getNode().scrollTo change to this.scrollView.scrollTo，
just remove the getNode() , error was gone.

Hope it can help you.

**Comment by biaji** [comment]
Text.propTypes.style,

should be replaced by:

`
const { TextPropTypes } = require('deprecated-react-native-prop-types');
`

**Comment by ptomasroos** [comment]
This has been resolved with #1185
