### ISSUE TITLE
react-native-scrollable-tab-view组件ScrollableTabBar初次渲染不显示underline

### ISSUE THREAD

**Issue by Oliverxyj123** [ptomasroos/react-native-scrollable-tab-view#952]

**Comment by Oliverxyj123** [comment]
new version will Resolve?

**Comment by jamessawyer** [comment]
Same issue with new version(V0.9.0). I checked source file 'ScrollableTabBar.js', I found 'this.props.scrollValue._value' was still not modified to 'this.props.scrollValue.__getValue' in new version.However, source code on github master branch is ok, I have no idea why this happened.
BTW, I use 'yarn add react-native-scrollable-tab-view@latest' install the lib.

**Comment by xntop** [comment]
Same issue

**Comment by stuChen** [comment]
Same issue

**Comment by ptomasroos** [comment]
Which rn versions are you on? Can you please provide a repo which reproduces this

**Comment by jamessawyer** [comment]
I can provide some snapshots in my local node_modules
react native project package.json file
<img width="606" alt="packagejsonfile" src="https://user-images.githubusercontent.com/22496982/48253133-203df400-e439-11e8-8fd1-73436390d2a1.png">

node_modules/react-native-scrollable-tab-view/package.json
<img width="1053" alt="packjsoninnodemodule" src="https://user-images.githubusercontent.com/22496982/48253186-3c419580-e439-11e8-8814-6472dae5e246.png">

node_modules/react-native-scrollable-tab-view/ScrollableTabBar.js
<img width="1045" alt="sourcefile" src="https://user-images.githubusercontent.com/22496982/48253223-58ddcd80-e439-11e8-8dcb-557da5954afb.png">

**Comment by ptomasroos** [comment]
Released as 0.10.0 my bad! Thanks
