### ISSUE TITLE
tabLabel doesn't show all the letters when using Android 9

### ISSUE THREAD

**Issue by coolguy001tv** [ptomasroos/react-native-scrollable-tab-view#962]
## Steps to Reproduce
See the demo [here](https://snack.expo.io/@coolguy/scroll-test) 
Here's the source code: 
```
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';

// You can import from local files
import NavBar from 'react-native-scrollable-tab-view';

export default class App extends React.Component {
  render() {
    return (
      <View style={{flex: 1,marginTop:20}}>
                <NavBar>
                    <View
                        tabLabel="abcd"
                    />
                    <View
                        tabLabel="efgh"
                    />
                </NavBar>

            </View>
    );
  }
}
```

You can see the tabs are 'abcd' and 'efgh' in the example above.
But in my phone (ONE PLUS 6 with Android 9.0.1) , the tabs only show 'abc' and 'efg'

## Expected Behavior
Show the right tab.
(I found it ok in android 7)

Here's my screenshot.

![47bfeb3df7a99e33dbbf1b83c91229d](https://user-images.githubusercontent.com/936825/49326959-becef800-f594-11e8-99d1-3ce517d43d56.jpg)

**Comment by ibrahemid** [comment]
i have OnePlus device running on the android pi as well, i believe its something related to the default style for the  tabBarText , i was able to fix the letter limit by overriding the Text-Style , try changing the text size or the fontFamily . 

this worked for me 😋 

 ```
<ScrollableTabView
    //other ScrollableTabView styles 
    tabBarTextStyleStyle={{
    fontFamily:'anything'
    //strange , but worked
    //even if the font doesn't exist it will work
    //other ScrollableTabView styles 
                        }}
                   >
```

Screenshots
https://imgur.com/a/hjG7ETP

**Comment by coolguy001tv** [comment]
@ibrahemid Thanks a lot. Setting the fontFamily to anything (even empty string) is ok for me. But it seems that setting fontSize doesn't work for me. However, it's a solution. Yet I don't know why, either.

**Comment by coolguy001tv** [comment]
Actually, this is related to https://github.com/facebook/react-native/issues/15114#issue-244222321 or https://github.com/facebook/react-native/issues/25481#issue-463931704 . If someone needs more info, check there.

**Comment by ibrahemid** [comment]
👍
