### ISSUE TITLE
Tab 栏点击没任何反应，不会切换

### ISSUE THREAD

**Issue by houwhu** [ptomasroos/react-native-scrollable-tab-view#965]
#### Tab 栏点击没任何反应，不会切换

我用的版本是： 
```
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
    "react-native-scrollable-tab-view": "^0.10.0",
```

**Comment by fancyzhe** [comment]
在安卓上点击没有任何反应，不能切换

**Comment by fancyzhe** [comment]
//源码
<ScrollableTabView
                initialPage={1}
                ref={(tabView) => {
                    this.tabView = tabView;
                }}
                onScroll={
                    (position) => {
                        console.log('滑动时的位置：' + position);
                    }
                }
                locked={false}
                tabBarPosition="overlayTop"
                prerenderingSiblingsNumber={1}
                renderTabBar={() => <DefaultTabBar />}
                // renderTabBar={() => <ScrollableTabBar />}
                tabBarBackgroundColor='#fff'
                tabBarActiveTextColor='#067DC6'
                tabBarInactiveTextColor='#666'
                tabBarUnderlineStyle={styles.underLine}
            >
                {
                    tabsContent.map((item, index) => <Text key={index} tabLabel={item.title}>{item.content}</Text>)
                }
</ScrollableTabView>


在iOS上是不可以滑动，只可以点击切换。安卓上是点击也切换不了，滑动也切换不了。

**Comment by fancyzhe** [comment]
加了一个onChange={(...e)=>console.log(e)}
在iOS端就不可以切换tab了，那怎么改写切换tab时的回调呢

**Comment by houwhu** [comment]
> //源码
> <ScrollableTabView
> initialPage={1}
> ref={(tabView) => {
> this.tabView = tabView;
> }}
> onScroll={
> (position) => {
> console.log('滑动时的位置：' + position);
> }
> }
> locked={false}
> tabBarPosition="overlayTop"
> prerenderingSiblingsNumber={1}
> renderTabBar={() => }
> // renderTabBar={() => }
> tabBarBackgroundColor='#fff'
> tabBarActiveTextColor='#067DC6'
> tabBarInactiveTextColor='#666'
> tabBarUnderlineStyle={styles.underLine}
> >
> {
> tabsContent.map((item, index) => {item.content})
> }
> 在iOS上是不可以滑动，只可以点击切换。安卓上是点击也切换不了，滑动也切换不了。

在外层组件上加上style={{flex: 1}}试试
