### ISSUE TITLE
change active tab dynamic

### ISSUE THREAD

**Issue by Mrezagolbaba** [ptomasroos/react-native-scrollable-tab-view#988]
i want to change active tab by pass params of navigation is this true?

`   
        constructor(props){
                       super(props);
                        this.state={
                       initialPage:'',
                      activeTabValue:''
                }
           }

    async componentDidMount(){
        const {Params} = this.props.navigation.state;
            if ( Params.T===1) {
             await   this.setState({ activeTabValue: 0 });
            } else
               await this.setState({  activeTabValue: 1 })
    }

           <ScrollableTabView
                    prerenderingSiblingsNumber={3}
                    initialPage={this.state.activeTabValue}
                    tabBarBackgroundColor={them.white}
                    tabBarActiveTextColor={them.black}
                    tabBarInactiveTextColor={them.borderColor}
                    tabBarUnderlineStyle={{backgroundColor:them.green}}
                    renderTabBar={() => <DefaultTabBar />}
                >
`

**Comment by afzal-ali27** [comment]
@Mrezagolbaba  How did you achieve this?
